export type ShopStatus = 'Pending' | 'Verified' | 'In Review' | 'Suspended'

export type Shop = {
  key: string
  sl: string
  shopId: string
  name: string
  type: string
  category: string
  joiningDate: string
  status: ShopStatus
  owner: string
  email: string
  phone: string
  address: string
  description: string
}

export const SHOP_TYPES = [
  'Finance',
  'Agriculture',
  'Technology',
  'Environmental',
  'Food & Beverage',
  'Education',
  'Healthcare',
  'Retail',
  'Transport',
  'Manufacturing',
  'Entertainment',
  'Tourism',
] as const

export const SHOP_STATUSES: ShopStatus[] = [
  'Pending',
  'Verified',
  'In Review',
  'Suspended',
]

export const initialShops: Shop[] = [
  {
    key: '1',
    sl: '01',
    shopId: 'SKY-1001',
    name: 'Skyline Ventures',
    type: 'Finance',
    category: 'Investment',
    joiningDate: '15 July 2024',
    status: 'Pending',
    owner: 'Arman Karim',
    email: 'contact@skyline.io',
    phone: '+880 1722 330110',
    address: 'Dhaka, Bangladesh',
    description:
      'Investment advisory and wealth management for emerging-market founders.',
  },
  {
    key: '2',
    sl: '02',
    shopId: 'GRN-1002',
    name: 'GreenLeaf Foods',
    type: 'Agriculture',
    category: 'Organic Produce',
    joiningDate: '22 August 2024',
    status: 'Verified',
    owner: 'Nusrat Rahman',
    email: 'hello@greenleaffoods.com',
    phone: '+880 1711 221133',
    address: 'Sylhet, Bangladesh',
    description: 'Farm-to-table organic produce supplier.',
  },
  {
    key: '3',
    sl: '03',
    shopId: 'TCH-1003',
    name: 'TechNova',
    type: 'Technology',
    category: 'Software Development',
    joiningDate: '30 September 2024',
    status: 'In Review',
    owner: 'Hasib Ali',
    email: 'team@technova.dev',
    phone: '+880 1777 445566',
    address: 'Chittagong, Bangladesh',
    description: 'Product studio building bespoke SaaS tooling.',
  },
  {
    key: '4',
    sl: '04',
    shopId: 'AQP-1004',
    name: 'AquaPure',
    type: 'Environmental',
    category: 'Water Purification',
    joiningDate: '05 October 2024',
    status: 'Verified',
    owner: 'Tania Chowdhury',
    email: 'support@aquapure.com',
    phone: '+880 1811 998877',
    address: 'Khulna, Bangladesh',
    description:
      'Clean-water systems for residential and industrial customers.',
  },
  {
    key: '5',
    sl: '05',
    shopId: 'URB-1005',
    name: 'Urban Bites',
    type: 'Food & Beverage',
    category: 'Fast Food',
    joiningDate: '12 October 2024',
    status: 'Pending',
    owner: 'Rakib Hossain',
    email: 'orders@urbanbites.com',
    phone: '+880 1700 112233',
    address: 'Dhaka, Bangladesh',
    description: 'Quick-service restaurants across metro areas.',
  },
  {
    key: '6',
    sl: '06',
    shopId: 'BRP-1006',
    name: 'Bright Path Education',
    type: 'Education',
    category: 'Online Courses',
    joiningDate: '18 October 2024',
    status: 'Verified',
    owner: 'Sumaiya Akter',
    email: 'info@brightpath.edu',
    phone: '+880 1900 332211',
    address: 'Dhaka, Bangladesh',
    description: 'Online learning platform for professional upskilling.',
  },
  {
    key: '7',
    sl: '07',
    shopId: 'VTL-1007',
    name: 'Vital Health',
    type: 'Healthcare',
    category: 'Pharmacy',
    joiningDate: '25 October 2024',
    status: 'Suspended',
    owner: 'Imran Chowdhury',
    email: 'care@vitalhealth.com',
    phone: '+880 1600 445577',
    address: 'Rajshahi, Bangladesh',
    description: 'Chain of community pharmacies and clinics.',
  },
  {
    key: '8',
    sl: '08',
    shopId: 'NOF-1008',
    name: 'Nova Fashion',
    type: 'Retail',
    category: 'Clothing',
    joiningDate: '02 November 2024',
    status: 'Verified',
    owner: 'Mousumi Akter',
    email: 'shop@novafashion.com',
    phone: '+880 1555 667788',
    address: 'Gulshan, Dhaka',
    description: 'Modern apparel for everyday wear.',
  },
  {
    key: '9',
    sl: '09',
    shopId: 'CTR-1009',
    name: 'CityRide',
    type: 'Transport',
    category: 'Ride Sharing',
    joiningDate: '10 November 2024',
    status: 'In Review',
    owner: 'Sabbir Khan',
    email: 'help@cityride.co',
    phone: '+880 1411 998866',
    address: 'Dhaka, Bangladesh',
    description: 'Urban ride-sharing and parcel delivery platform.',
  },
  {
    key: '10',
    sl: '10',
    shopId: 'SPC-1010',
    name: 'SparkCraft',
    type: 'Manufacturing',
    category: 'Artisan Goods',
    joiningDate: '15 November 2024',
    status: 'Pending',
    owner: 'Mahir Chowdhury',
    email: 'hello@sparkcraft.store',
    phone: '+880 1322 554411',
    address: 'Comilla, Bangladesh',
    description: 'Handcrafted homeware and gifts.',
  },
  {
    key: '11',
    sl: '11',
    shopId: 'NEB-1011',
    name: 'Neon Beats',
    type: 'Entertainment',
    category: 'Music Streaming',
    joiningDate: '22 November 2024',
    status: 'Verified',
    owner: 'Rafi Islam',
    email: 'contact@neonbeats.fm',
    phone: '+880 1822 665544',
    address: 'Dhaka, Bangladesh',
    description: 'Music streaming service focused on South Asian artists.',
  },
  {
    key: '12',
    sl: '12',
    shopId: 'TRB-1012',
    name: 'Trailblaze Travel',
    type: 'Tourism',
    category: 'Booking',
    joiningDate: '30 November 2024',
    status: 'In Review',
    owner: 'Oishee Das',
    email: 'bookings@trailblaze.travel',
    phone: '+880 1999 004411',
    address: "Cox's Bazar, Bangladesh",
    description: 'Curated holiday and expedition packages.',
  },
]
